---
  - name: Aruba switch
    gather_facts: false
    hosts:
    connection: local
    remote_user:
 
    #hosts: 1
    tasks:
        - name: Get output of show commands
          arubaos_switch_ssh_cli:
            ip: "{{ansible_host}}"
            user: "{{ansible_user}}"
            password: "{{ansible_password}}"
            show_command: ["show config"]
          register: output